syntax = "proto3";
package cafe.preparation.requests.v1;
option go_package = "github.com/pharos-ai-factory/ddd-hexagonal-cqrs-es-eda-microservices-multilingual/services/storefront/contracts/requests/generated/cafe/requests/v1/contexts/preparation;preparationv1";

message Ticket {
  string id = 1;
  string order_id = 2;
  string customer_id = 3;
  string instructions = 4;
  string status = 5;
}

message LoadedTicket {
  bool exists = 1;
  uint64 version = 2;
  Ticket state = 3;
}

message Tickets {
  repeated LoadedTicket items = 1;
  bool paged = 2;
  optional string next_id = 3;
}
